### PR TITLE
Add three fields to GPS: Active, Source status, Name

### PR DESCRIPTION
**Pull request by dayrover**
A small patch to expand the information on the GPS. I expanded this information while try to debug location problem.
Also included are some null checks to avoid null warnings for fiels for sensors that do not exist!

### CODE REVIEW

**Comment by yohanboniface** [comment]
Thanks, look good! :)
I've switched from Ubuntu to Arch, and I haven't reinstalled the dev tools. Are you able to build a new version so we can put it on the store? Otherwise I'll try installing dev tools, but I'm not sure when I'll have time for that.
Thanks again!

**Comment by dayrover** [comment]
Hi Yohan,


On 14.06.2016 10:36, Yohan Boniface wrote:
>
> Thanks, look good! :)
> I've switched from Ubuntu to Arch, and I haven't reinstalled the dev
> tools. Are you able to build a new version so we can put it on the
> store? Otherwise I'll try installing dev tools, but I'm not sure when
> I'll have time for that.
>
Oh the dreaded distro hoping! I have Arch on a few embedded machines.
However my daily work laptop stays on Ubuntu which is nice an stable.
Since the Ubuntu SDK is a package monster and does a heap of schroot
mounts I only have it installed in a VirtualBox! Disadvantage is the
Android Emulator does not work in visualisation so I have to test on my
phone!

I attached the build with the version bumped to 0.0.3.

Thanks for the useful app,

Michael

**Comment by yohanboniface** [comment]
> However my daily work laptop stays on Ubuntu which is nice an stable.

Arch is sooo stable ;)

> I attached the build with the version bumped to 0.0.3.

Attached where? :)

**Comment by dayrover** [comment]
Hi Yohan,


On 18.06.2016 21:08, Yohan Boniface wrote:
>
>     However my daily work laptop stays on Ubuntu which is nice an stable.
>
> Arch is sooo stable ;)
>
>     I attached the build with the version bumped to 0.0.3.
>
> Attached where? :)
>

The email went out with the attachment. Looks like github strips out the
attachments to replies. Can you send me your direct email address or if
you would prefer I can place it on a server where you can download it from.

Cheers,

Michael

**Comment by yohanboniface** [comment]
hi at {firstname}{lastname} dot me :)

**Pull request merged**
